//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMART_ACC_DB_2022Entities : DbContext
    {
        public SMART_ACC_DB_2022Entities()
            : base("name=SMART_ACC_DB_2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BANK> T_BANK { get; set; }
        public virtual DbSet<T_BANK_ACOUNT> T_BANK_ACOUNT { get; set; }
        public virtual DbSet<T_BILL_IN> T_BILL_IN { get; set; }
        public virtual DbSet<T_BILL_IN_TRANSACTION> T_BILL_IN_TRANSACTION { get; set; }
        public virtual DbSet<T_BILL_OUT> T_BILL_OUT { get; set; }
        public virtual DbSet<T_BILL_OUT_TRANSACTION> T_BILL_OUT_TRANSACTION { get; set; }
        public virtual DbSet<T_BILL_TYPE> T_BILL_TYPE { get; set; }
        public virtual DbSet<T_BOND_DELETE> T_BOND_DELETE { get; set; }
        public virtual DbSet<T_BOND_DELETE_ITEM> T_BOND_DELETE_ITEM { get; set; }
        public virtual DbSet<T_BOND_ENTRY> T_BOND_ENTRY { get; set; }
        public virtual DbSet<T_BOND_ENTRY_ITEM> T_BOND_ENTRY_ITEM { get; set; }
        public virtual DbSet<T_BOND_OUT> T_BOND_OUT { get; set; }
        public virtual DbSet<T_BOND_OUT_ITEM> T_BOND_OUT_ITEM { get; set; }
        public virtual DbSet<T_BONDS_TYPE> T_BONDS_TYPE { get; set; }
        public virtual DbSet<T_BOXES> T_BOXES { get; set; }
        public virtual DbSet<T_BRANCH> T_BRANCH { get; set; }
        public virtual DbSet<T_CASH_ACOUNT> T_CASH_ACOUNT { get; set; }
        public virtual DbSet<T_CASH_TRANSACTION> T_CASH_TRANSACTION { get; set; }
        public virtual DbSet<T_COMPANY_INFO> T_COMPANY_INFO { get; set; }
        public virtual DbSet<T_CURNCY> T_CURNCY { get; set; }
        public virtual DbSet<T_CURNCY_BANK> T_CURNCY_BANK { get; set; }
        public virtual DbSet<T_CUSTOMER> T_CUSTOMER { get; set; }
        public virtual DbSet<T_EMLOEE_ACCOUNT> T_EMLOEE_ACCOUNT { get; set; }
        public virtual DbSet<T_EMPLOEE> T_EMPLOEE { get; set; }
        public virtual DbSet<T_EMPLOEE_SALARY> T_EMPLOEE_SALARY { get; set; }
        public virtual DbSet<T_EXPENCES> T_EXPENCES { get; set; }
        public virtual DbSet<T_EXPENCES_ACCOUNT> T_EXPENCES_ACCOUNT { get; set; }
        public virtual DbSet<T_EXPENSES_TYPE> T_EXPENSES_TYPE { get; set; }
        public virtual DbSet<T_INVOICE_PAY> T_INVOICE_PAY { get; set; }
        public virtual DbSet<T_INVOICE_PAY_BACK> T_INVOICE_PAY_BACK { get; set; }
        public virtual DbSet<T_INVOICE_PAY_BACK_TRANSACTION> T_INVOICE_PAY_BACK_TRANSACTION { get; set; }
        public virtual DbSet<T_INVOICE_PAY_BONES> T_INVOICE_PAY_BONES { get; set; }
        public virtual DbSet<T_INVOICE_PAY_ITEM> T_INVOICE_PAY_ITEM { get; set; }
        public virtual DbSet<T_INVOICE_PAY_ITEM_BACK> T_INVOICE_PAY_ITEM_BACK { get; set; }
        public virtual DbSet<T_INVOICE_PAY_TRANSACTION> T_INVOICE_PAY_TRANSACTION { get; set; }
        public virtual DbSet<T_INVOICE_PAY_TYPE> T_INVOICE_PAY_TYPE { get; set; }
        public virtual DbSet<T_INVOICE_SALES> T_INVOICE_SALES { get; set; }
        public virtual DbSet<T_INVOICE_SALES_BACK> T_INVOICE_SALES_BACK { get; set; }
        public virtual DbSet<T_INVOICE_SALES_BACK_TRANSACTION> T_INVOICE_SALES_BACK_TRANSACTION { get; set; }
        public virtual DbSet<T_INVOICE_SALES_BONES> T_INVOICE_SALES_BONES { get; set; }
        public virtual DbSet<T_INVOICE_SALES_ITEM> T_INVOICE_SALES_ITEM { get; set; }
        public virtual DbSet<T_INVOICE_SALES_ITEM_BACK> T_INVOICE_SALES_ITEM_BACK { get; set; }
        public virtual DbSet<T_INVOICE_SALES_TRANSACTION> T_INVOICE_SALES_TRANSACTION { get; set; }
        public virtual DbSet<T_INVOICE_TYPE> T_INVOICE_TYPE { get; set; }
        public virtual DbSet<T_ITEM_BARCODE> T_ITEM_BARCODE { get; set; }
        public virtual DbSet<T_ITEM_CATIGORY> T_ITEM_CATIGORY { get; set; }
        public virtual DbSet<T_ITEM_DETAILS> T_ITEM_DETAILS { get; set; }
        public virtual DbSet<T_ITEM_PICTURE> T_ITEM_PICTURE { get; set; }
        public virtual DbSet<T_ITEM_STORE> T_ITEM_STORE { get; set; }
        public virtual DbSet<T_ITEM_SUB_CATEGORY> T_ITEM_SUB_CATEGORY { get; set; }
        public virtual DbSet<T_ITEM_TYPE> T_ITEM_TYPE { get; set; }
        public virtual DbSet<T_ITEMS> T_ITEMS { get; set; }
        public virtual DbSet<T_LOCAL_ACCOUNT> T_LOCAL_ACCOUNT { get; set; }
        public virtual DbSet<T_LOCAL_ACCOUNT_TYPE> T_LOCAL_ACCOUNT_TYPE { get; set; }
        public virtual DbSet<T_MAIN_CASH> T_MAIN_CASH { get; set; }
        public virtual DbSet<T_STORE> T_STORE { get; set; }
        public virtual DbSet<T_STORE_BRANCH> T_STORE_BRANCH { get; set; }
        public virtual DbSet<T_STORE_ENTRY_TRANSAQTION> T_STORE_ENTRY_TRANSAQTION { get; set; }
        public virtual DbSet<T_STORE_OUT_TRANSAQTION> T_STORE_OUT_TRANSAQTION { get; set; }
        public virtual DbSet<T_TAX> T_TAX { get; set; }
        public virtual DbSet<T_TAX_TRANSACTION> T_TAX_TRANSACTION { get; set; }
        public virtual DbSet<T_TRED_TYPE> T_TRED_TYPE { get; set; }
        public virtual DbSet<T_UNIT_PICTURE> T_UNIT_PICTURE { get; set; }
        public virtual DbSet<T_UNIT_SIZE> T_UNIT_SIZE { get; set; }
        public virtual DbSet<T_UNIT_TYPE> T_UNIT_TYPE { get; set; }
        public virtual DbSet<T_VENDOR> T_VENDOR { get; set; }
    }
}
