//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BANK()
        {
            this.T_BANK_ACOUNT = new HashSet<T_BANK_ACOUNT>();
            this.T_CURNCY_BANK = new HashSet<T_CURNCY_BANK>();
        }
    
        public decimal bank_id { get; set; }
        public Nullable<decimal> bank_code { get; set; }
        public string bank_name { get; set; }
        public string bank_adress { get; set; }
        public string bank_phone { get; set; }
        public string bank_branch { get; set; }
        public string bank_notion { get; set; }
        public Nullable<bool> bank_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BANK_ACOUNT> T_BANK_ACOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CURNCY_BANK> T_CURNCY_BANK { get; set; }
    }
}
