//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BANK_ACOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BANK_ACOUNT()
        {
            this.T_BILL_IN = new HashSet<T_BILL_IN>();
            this.T_BILL_OUT = new HashSet<T_BILL_OUT>();
            this.T_CASH_TRANSACTION = new HashSet<T_CASH_TRANSACTION>();
        }
    
        public decimal bank_a_id { get; set; }
        public Nullable<decimal> bank_a_code { get; set; }
        public string bank_a_name { get; set; }
        public Nullable<System.DateTime> bank_a_start_date { get; set; }
        public Nullable<decimal> bank_a_start_balance { get; set; }
        public Nullable<decimal> bank_a_zero_balance { get; set; }
        public Nullable<decimal> bank_a_balance { get; set; }
        public Nullable<bool> bank_a_state { get; set; }
        public string bank_a_note { get; set; }
        public Nullable<decimal> curncy_id { get; set; }
        public Nullable<decimal> bank_id { get; set; }
        public Nullable<decimal> cash_id { get; set; }
    
        public virtual T_BANK T_BANK { get; set; }
        public virtual T_CURNCY T_CURNCY { get; set; }
        public virtual T_MAIN_CASH T_MAIN_CASH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_IN> T_BILL_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_OUT> T_BILL_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CASH_TRANSACTION> T_CASH_TRANSACTION { get; set; }
    }
}
