//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BILL_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BILL_TYPE()
        {
            this.T_BILL_IN = new HashSet<T_BILL_IN>();
            this.T_BILL_OUT = new HashSet<T_BILL_OUT>();
        }
    
        public decimal bill_type_id { get; set; }
        public Nullable<decimal> bill_type_code { get; set; }
        public string bill_type { get; set; }
        public Nullable<bool> bill_type_state { get; set; }
        public string bill_type_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_IN> T_BILL_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_OUT> T_BILL_OUT { get; set; }
    }
}
