//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BOND_DELETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BOND_DELETE()
        {
            this.T_BOND_DELETE_ITEM = new HashSet<T_BOND_DELETE_ITEM>();
        }
    
        public decimal delet_bond_id { get; set; }
        public Nullable<decimal> delet_bond_code { get; set; }
        public Nullable<System.DateTime> delet_bond_date { get; set; }
        public Nullable<System.TimeSpan> delet_bond_time { get; set; }
        public string delet_bond_text { get; set; }
        public Nullable<bool> delet_bond_state { get; set; }
        public string delet_bond_note { get; set; }
        public Nullable<decimal> bond_type_id { get; set; }
        public Nullable<decimal> inv_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_DELETE_ITEM> T_BOND_DELETE_ITEM { get; set; }
        public virtual T_BONDS_TYPE T_BONDS_TYPE { get; set; }
    }
}
