//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BONDS_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BONDS_TYPE()
        {
            this.T_BOND_DELETE = new HashSet<T_BOND_DELETE>();
            this.T_BOND_ENTRY = new HashSet<T_BOND_ENTRY>();
            this.T_BOND_OUT = new HashSet<T_BOND_OUT>();
            this.T_STORE_ENTRY_TRANSAQTION = new HashSet<T_STORE_ENTRY_TRANSAQTION>();
            this.T_STORE_OUT_TRANSAQTION = new HashSet<T_STORE_OUT_TRANSAQTION>();
        }
    
        public decimal bond_type_id { get; set; }
        public Nullable<decimal> bond_type_code { get; set; }
        public string bond_type_name { get; set; }
        public Nullable<bool> bond_type_state { get; set; }
        public string bond_type_nots { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_DELETE> T_BOND_DELETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_ENTRY> T_BOND_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_OUT> T_BOND_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_STORE_ENTRY_TRANSAQTION> T_STORE_ENTRY_TRANSAQTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_STORE_OUT_TRANSAQTION> T_STORE_OUT_TRANSAQTION { get; set; }
    }
}
