//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BRANCH()
        {
            this.T_BILL_IN_TRANSACTION = new HashSet<T_BILL_IN_TRANSACTION>();
            this.T_BILL_OUT_TRANSACTION = new HashSet<T_BILL_OUT_TRANSACTION>();
            this.T_CURNCY = new HashSet<T_CURNCY>();
            this.T_EMPLOEE = new HashSet<T_EMPLOEE>();
            this.T_INVOICE_PAY_BACK_TRANSACTION = new HashSet<T_INVOICE_PAY_BACK_TRANSACTION>();
            this.T_INVOICE_PAY_TRANSACTION = new HashSet<T_INVOICE_PAY_TRANSACTION>();
            this.T_INVOICE_SALES_BACK_TRANSACTION = new HashSet<T_INVOICE_SALES_BACK_TRANSACTION>();
            this.T_INVOICE_SALES_TRANSACTION = new HashSet<T_INVOICE_SALES_TRANSACTION>();
            this.T_MAIN_CASH = new HashSet<T_MAIN_CASH>();
            this.T_STORE_BRANCH = new HashSet<T_STORE_BRANCH>();
        }
    
        public decimal bran_id { get; set; }
        public Nullable<decimal> bran_code { get; set; }
        public string bran_name { get; set; }
        public string bran_adress { get; set; }
        public string bran_phone { get; set; }
        public string bran_mobile { get; set; }
        public string bran_location { get; set; }
        public Nullable<System.DateTime> bran_opendate { get; set; }
        public Nullable<bool> bran_stat { get; set; }
        public Nullable<decimal> com_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_IN_TRANSACTION> T_BILL_IN_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_OUT_TRANSACTION> T_BILL_OUT_TRANSACTION { get; set; }
        public virtual T_COMPANY_INFO T_COMPANY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CURNCY> T_CURNCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EMPLOEE> T_EMPLOEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BACK_TRANSACTION> T_INVOICE_PAY_BACK_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_TRANSACTION> T_INVOICE_PAY_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BACK_TRANSACTION> T_INVOICE_SALES_BACK_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_TRANSACTION> T_INVOICE_SALES_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MAIN_CASH> T_MAIN_CASH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_STORE_BRANCH> T_STORE_BRANCH { get; set; }
    }
}
