//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CASH_TRANSACTION
    {
        public decimal cash_tra_id { get; set; }
        public Nullable<decimal> cash_tra_code { get; set; }
        public string cash_tra_name { get; set; }
        public Nullable<System.DateTime> cash_tra_date { get; set; }
        public Nullable<System.TimeSpan> cash_tra_time { get; set; }
        public Nullable<decimal> cash_tra_amount { get; set; }
        public Nullable<decimal> cash_tra_total { get; set; }
        public Nullable<bool> cash_tra_type { get; set; }
        public Nullable<bool> cash_tra_stat { get; set; }
        public string cash_tra_note { get; set; }
        public Nullable<decimal> bank_a_id { get; set; }
        public Nullable<decimal> cash_a_id { get; set; }
        public Nullable<decimal> cash_id { get; set; }
    
        public virtual T_BANK_ACOUNT T_BANK_ACOUNT { get; set; }
        public virtual T_CASH_ACOUNT T_CASH_ACOUNT { get; set; }
        public virtual T_MAIN_CASH T_MAIN_CASH { get; set; }
    }
}
