//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPANY_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_COMPANY_INFO()
        {
            this.T_BRANCH = new HashSet<T_BRANCH>();
        }
    
        public decimal com_id { get; set; }
        public Nullable<decimal> com_code { get; set; }
        public string com_name { get; set; }
        public string com_adress1 { get; set; }
        public string com_adress2 { get; set; }
        public string com_adress3 { get; set; }
        public string com_mobile1 { get; set; }
        public string com_mobile2 { get; set; }
        public string com_mobile3 { get; set; }
        public string com_fax { get; set; }
        public string com_title { get; set; }
        public string com_notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BRANCH> T_BRANCH { get; set; }
    }
}
