//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CURNCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CURNCY()
        {
            this.T_BANK_ACOUNT = new HashSet<T_BANK_ACOUNT>();
            this.T_BILL_IN_TRANSACTION = new HashSet<T_BILL_IN_TRANSACTION>();
            this.T_BILL_OUT_TRANSACTION = new HashSet<T_BILL_OUT_TRANSACTION>();
            this.T_CURNCY_BANK = new HashSet<T_CURNCY_BANK>();
            this.T_INVOICE_PAY_BACK_TRANSACTION = new HashSet<T_INVOICE_PAY_BACK_TRANSACTION>();
            this.T_INVOICE_PAY_TRANSACTION = new HashSet<T_INVOICE_PAY_TRANSACTION>();
            this.T_INVOICE_SALES_BACK_TRANSACTION = new HashSet<T_INVOICE_SALES_BACK_TRANSACTION>();
            this.T_INVOICE_SALES_TRANSACTION = new HashSet<T_INVOICE_SALES_TRANSACTION>();
        }
    
        public decimal curncy_id { get; set; }
        public Nullable<decimal> curncy_code { get; set; }
        public string curncy_name { get; set; }
        public string curncy_type { get; set; }
        public string curncy_nation { get; set; }
        public Nullable<decimal> curncy_value { get; set; }
        public Nullable<bool> curncy_state { get; set; }
        public string curncy_note { get; set; }
        public Nullable<decimal> bran_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BANK_ACOUNT> T_BANK_ACOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_IN_TRANSACTION> T_BILL_IN_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_OUT_TRANSACTION> T_BILL_OUT_TRANSACTION { get; set; }
        public virtual T_BRANCH T_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CURNCY_BANK> T_CURNCY_BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BACK_TRANSACTION> T_INVOICE_PAY_BACK_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_TRANSACTION> T_INVOICE_PAY_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BACK_TRANSACTION> T_INVOICE_SALES_BACK_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_TRANSACTION> T_INVOICE_SALES_TRANSACTION { get; set; }
    }
}
