//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CURNCY_BANK
    {
        public decimal curncy_bank_id { get; set; }
        public Nullable<decimal> curncy_bank_code { get; set; }
        public string curncy_bank_name { get; set; }
        public Nullable<bool> curncy_bank_state { get; set; }
        public Nullable<decimal> bank_id { get; set; }
        public Nullable<decimal> curncy_id { get; set; }
    
        public virtual T_BANK T_BANK { get; set; }
        public virtual T_CURNCY T_CURNCY { get; set; }
    }
}
