//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMPLOEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EMPLOEE()
        {
            this.T_EMLOEE_ACCOUNT = new HashSet<T_EMLOEE_ACCOUNT>();
            this.T_EMPLOEE_SALARY = new HashSet<T_EMPLOEE_SALARY>();
        }
    
        public decimal emp_id { get; set; }
        public Nullable<decimal> emp_code { get; set; }
        public string emp_name { get; set; }
        public string emp_nick_name { get; set; }
        public string emp_type { get; set; }
        public Nullable<int> emp_sal { get; set; }
        public string emp_w_hours { get; set; }
        public Nullable<System.DateTime> emp_s_date { get; set; }
        public string emp_adress { get; set; }
        public string emp_mobile { get; set; }
        public string emp_w_position { get; set; }
        public Nullable<decimal> bran_id { get; set; }
        public Nullable<bool> emp_state { get; set; }
        public string emp_note { get; set; }
    
        public virtual T_BRANCH T_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EMLOEE_ACCOUNT> T_EMLOEE_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EMPLOEE_SALARY> T_EMPLOEE_SALARY { get; set; }
    }
}
