//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMLOEE_ACCOUNT
    {
        public decimal imp_a_id { get; set; }
        public Nullable<decimal> imp_a_code { get; set; }
        public Nullable<System.DateTime> imp_a_date { get; set; }
        public Nullable<System.TimeSpan> imp_a_time { get; set; }
        public Nullable<decimal> imp_a_balance { get; set; }
        public Nullable<decimal> emp_id { get; set; }
        public Nullable<bool> imp_a_state { get; set; }
        public string imp_a_note { get; set; }
    
        public virtual T_EMPLOEE T_EMPLOEE { get; set; }
    }
}
