//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXPENSES_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EXPENSES_TYPE()
        {
            this.T_EXPENCES = new HashSet<T_EXPENCES>();
        }
    
        public decimal eex_type_id { get; set; }
        public Nullable<decimal> eex_type_code { get; set; }
        public string eex_type_name { get; set; }
        public byte[] eex_type_details { get; set; }
        public Nullable<bool> eex_type_state { get; set; }
        public string eex_type_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EXPENCES> T_EXPENCES { get; set; }
    }
}
