//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXPENCES_ACCOUNT
    {
        public decimal exp_acount_id { get; set; }
        public Nullable<decimal> exp_acount_code { get; set; }
        public string exp_acount_name { get; set; }
        public string exp_acount_nike_name { get; set; }
        public Nullable<System.DateTime> exp_acount_start_data { get; set; }
        public Nullable<bool> exp_acount_state { get; set; }
        public string exp_acount_note { get; set; }
        public Nullable<decimal> exp_id { get; set; }
    
        public virtual T_EXPENCES T_EXPENCES { get; set; }
    }
}
