//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_SALES_TRANSACTION
    {
        public decimal sals_tran_id { get; set; }
        public Nullable<decimal> sals_tran_code { get; set; }
        public Nullable<System.DateTime> sals_tran_date { get; set; }
        public Nullable<System.TimeSpan> sals_tran_time { get; set; }
        public Nullable<decimal> cust_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> curncy_id { get; set; }
        public Nullable<decimal> sale_inv_id { get; set; }
        public Nullable<decimal> bran_id { get; set; }
        public Nullable<bool> sals_tran_state { get; set; }
        public string sals_tran_note { get; set; }
    
        public virtual T_BRANCH T_BRANCH { get; set; }
        public virtual T_CURNCY T_CURNCY { get; set; }
        public virtual T_CUSTOMER T_CUSTOMER { get; set; }
        public virtual T_INVOICE_SALES T_INVOICE_SALES { get; set; }
    }
}
