//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_SALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_INVOICE_SALES()
        {
            this.T_BILL_IN = new HashSet<T_BILL_IN>();
            this.T_BOND_OUT = new HashSet<T_BOND_OUT>();
            this.T_INVOICE_SALES_BACK = new HashSet<T_INVOICE_SALES_BACK>();
            this.T_INVOICE_SALES_BONES = new HashSet<T_INVOICE_SALES_BONES>();
            this.T_INVOICE_SALES_ITEM = new HashSet<T_INVOICE_SALES_ITEM>();
            this.T_INVOICE_SALES_TRANSACTION = new HashSet<T_INVOICE_SALES_TRANSACTION>();
        }
    
        public decimal sale_inv_id { get; set; }
        public Nullable<decimal> sale_inv_code { get; set; }
        public Nullable<System.DateTime> sale_inv_date { get; set; }
        public Nullable<System.TimeSpan> sale_inv_time { get; set; }
        public Nullable<System.DateTime> sale_inv_pay_date { get; set; }
        public string sale_inv_text { get; set; }
        public Nullable<decimal> cust_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> tax_per { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_plus { get; set; }
        public Nullable<decimal> discount_type { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> net { get; set; }
        public string sale_inv_adress { get; set; }
        public Nullable<decimal> pay_type_id { get; set; }
        public Nullable<decimal> inv_type_id { get; set; }
        public Nullable<bool> sale_inv_state { get; set; }
        public string sale_inv_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_IN> T_BILL_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_OUT> T_BOND_OUT { get; set; }
        public virtual T_CUSTOMER T_CUSTOMER { get; set; }
        public virtual T_INVOICE_PAY_TYPE T_INVOICE_PAY_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BACK> T_INVOICE_SALES_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BONES> T_INVOICE_SALES_BONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_ITEM> T_INVOICE_SALES_ITEM { get; set; }
        public virtual T_INVOICE_TYPE T_INVOICE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_TRANSACTION> T_INVOICE_SALES_TRANSACTION { get; set; }
    }
}
