//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_PAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_INVOICE_PAY()
        {
            this.T_BILL_OUT = new HashSet<T_BILL_OUT>();
            this.T_BOND_ENTRY = new HashSet<T_BOND_ENTRY>();
            this.T_INVOICE_PAY_BACK = new HashSet<T_INVOICE_PAY_BACK>();
            this.T_INVOICE_PAY_BONES = new HashSet<T_INVOICE_PAY_BONES>();
            this.T_INVOICE_PAY_ITEM = new HashSet<T_INVOICE_PAY_ITEM>();
            this.T_INVOICE_PAY_TRANSACTION = new HashSet<T_INVOICE_PAY_TRANSACTION>();
        }
    
        public decimal pay_inv_id { get; set; }
        public Nullable<decimal> pay_inv_code { get; set; }
        public Nullable<System.DateTime> pay_inv_date { get; set; }
        public Nullable<System.TimeSpan> pay_inv_time { get; set; }
        public Nullable<System.DateTime> pay_inv_pay_date { get; set; }
        public string pay_inv_text { get; set; }
        public Nullable<decimal> ven_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> tax_per { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_plus { get; set; }
        public Nullable<decimal> discount_type { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> net { get; set; }
        public string pay_inv_adress { get; set; }
        public Nullable<decimal> pay_type_id { get; set; }
        public Nullable<decimal> inv_type_id { get; set; }
        public Nullable<bool> pay_inv_state { get; set; }
        public string pay_inv_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BILL_OUT> T_BILL_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_ENTRY> T_BOND_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BACK> T_INVOICE_PAY_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BONES> T_INVOICE_PAY_BONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_ITEM> T_INVOICE_PAY_ITEM { get; set; }
        public virtual T_INVOICE_PAY_TYPE T_INVOICE_PAY_TYPE { get; set; }
        public virtual T_INVOICE_TYPE T_INVOICE_TYPE { get; set; }
        public virtual T_VENDOR T_VENDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_TRANSACTION> T_INVOICE_PAY_TRANSACTION { get; set; }
    }
}
