//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_PAY_BACK_TRANSACTION
    {
        public decimal pay_b_tran_id { get; set; }
        public Nullable<decimal> pay_b_tran_code { get; set; }
        public Nullable<System.DateTime> pay_b_tran_date { get; set; }
        public Nullable<System.TimeSpan> pay_b_tran_time { get; set; }
        public Nullable<decimal> ven_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> curncy_id { get; set; }
        public Nullable<decimal> pay_b_inv_id { get; set; }
        public Nullable<decimal> bran_id { get; set; }
        public Nullable<bool> pay_b_tran_state { get; set; }
        public string pay_b_tran_note { get; set; }
    
        public virtual T_BRANCH T_BRANCH { get; set; }
        public virtual T_CURNCY T_CURNCY { get; set; }
        public virtual T_INVOICE_PAY_BACK T_INVOICE_PAY_BACK { get; set; }
        public virtual T_VENDOR T_VENDOR { get; set; }
    }
}
