//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_PAY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_INVOICE_PAY_TYPE()
        {
            this.T_INVOICE_PAY = new HashSet<T_INVOICE_PAY>();
            this.T_INVOICE_PAY_BACK = new HashSet<T_INVOICE_PAY_BACK>();
            this.T_INVOICE_SALES_BACK = new HashSet<T_INVOICE_SALES_BACK>();
            this.T_INVOICE_SALES = new HashSet<T_INVOICE_SALES>();
        }
    
        public decimal pay_type_id { get; set; }
        public Nullable<decimal> pay_type_code { get; set; }
        public string pay_typ { get; set; }
        public Nullable<bool> pay_type_state { get; set; }
        public string pay_type_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY> T_INVOICE_PAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BACK> T_INVOICE_PAY_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BACK> T_INVOICE_SALES_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES> T_INVOICE_SALES { get; set; }
    }
}
