//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE_PAY_BONES
    {
        public decimal pay_inv_bon_id { get; set; }
        public Nullable<decimal> pay_inv_bon_code { get; set; }
        public Nullable<System.DateTime> pay_inv_bon_date { get; set; }
        public Nullable<System.TimeSpan> pay_inv_bon_time { get; set; }
        public string pay_inv_bon_text { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> pay_inv_bon_stae { get; set; }
        public string pay_inv_bon_note { get; set; }
        public Nullable<decimal> item_id { get; set; }
        public Nullable<decimal> pay_inv_id { get; set; }
        public Nullable<decimal> unit_size_id { get; set; }
        public Nullable<decimal> unit_type_id { get; set; }
    
        public virtual T_INVOICE_PAY T_INVOICE_PAY { get; set; }
        public virtual T_ITEMS T_ITEMS { get; set; }
        public virtual T_UNIT_SIZE T_UNIT_SIZE { get; set; }
        public virtual T_UNIT_TYPE T_UNIT_TYPE { get; set; }
    }
}
