//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ITEMS()
        {
            this.T_BOND_DELETE_ITEM = new HashSet<T_BOND_DELETE_ITEM>();
            this.T_BOND_ENTRY_ITEM = new HashSet<T_BOND_ENTRY_ITEM>();
            this.T_BOND_OUT_ITEM = new HashSet<T_BOND_OUT_ITEM>();
            this.T_INVOICE_PAY_BONES = new HashSet<T_INVOICE_PAY_BONES>();
            this.T_INVOICE_PAY_ITEM = new HashSet<T_INVOICE_PAY_ITEM>();
            this.T_INVOICE_PAY_ITEM_BACK = new HashSet<T_INVOICE_PAY_ITEM_BACK>();
            this.T_INVOICE_SALES_BONES = new HashSet<T_INVOICE_SALES_BONES>();
            this.T_INVOICE_SALES_ITEM = new HashSet<T_INVOICE_SALES_ITEM>();
            this.T_INVOICE_SALES_ITEM_BACK = new HashSet<T_INVOICE_SALES_ITEM_BACK>();
            this.T_ITEM_BARCODE = new HashSet<T_ITEM_BARCODE>();
            this.T_ITEM_DETAILS = new HashSet<T_ITEM_DETAILS>();
            this.T_ITEM_PICTURE = new HashSet<T_ITEM_PICTURE>();
            this.T_ITEM_STORE = new HashSet<T_ITEM_STORE>();
            this.T_UNIT_PICTURE = new HashSet<T_UNIT_PICTURE>();
        }
    
        public decimal item_id { get; set; }
        public Nullable<decimal> item_code { get; set; }
        public string item_name { get; set; }
        public string item_nike_name { get; set; }
        public Nullable<int> item_max_count { get; set; }
        public Nullable<int> item_min_count { get; set; }
        public Nullable<int> item_limt_count { get; set; }
        public Nullable<decimal> item_cost_price { get; set; }
        public Nullable<decimal> item_buy_price { get; set; }
        public Nullable<decimal> item_sales_price { get; set; }
        public Nullable<decimal> item_avr_price { get; set; }
        public Nullable<decimal> item_fact_price { get; set; }
        public Nullable<decimal> item_discount_amount { get; set; }
        public Nullable<int> item_discount_persenteg { get; set; }
        public Nullable<int> item_tax_persenteg { get; set; }
        public Nullable<bool> item_state { get; set; }
        public string item_note { get; set; }
        public Nullable<decimal> sab_id { get; set; }
        public Nullable<decimal> unit_size_id { get; set; }
        public Nullable<decimal> box_id { get; set; }
        public Nullable<decimal> item_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_DELETE_ITEM> T_BOND_DELETE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_ENTRY_ITEM> T_BOND_ENTRY_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BOND_OUT_ITEM> T_BOND_OUT_ITEM { get; set; }
        public virtual T_BOXES T_BOXES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BONES> T_INVOICE_PAY_BONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_ITEM> T_INVOICE_PAY_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_ITEM_BACK> T_INVOICE_PAY_ITEM_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_BONES> T_INVOICE_SALES_BONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_ITEM> T_INVOICE_SALES_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_SALES_ITEM_BACK> T_INVOICE_SALES_ITEM_BACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ITEM_BARCODE> T_ITEM_BARCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ITEM_DETAILS> T_ITEM_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ITEM_PICTURE> T_ITEM_PICTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ITEM_STORE> T_ITEM_STORE { get; set; }
        public virtual T_ITEM_SUB_CATEGORY T_ITEM_SUB_CATEGORY { get; set; }
        public virtual T_ITEM_TYPE T_ITEM_TYPE { get; set; }
        public virtual T_UNIT_SIZE T_UNIT_SIZE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNIT_PICTURE> T_UNIT_PICTURE { get; set; }
    }
}
