//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ITEM_STORE
    {
        public decimal item_store_id { get; set; }
        public Nullable<decimal> item_store_code { get; set; }
        public Nullable<System.DateTime> item_store_date { get; set; }
        public string item_store_place { get; set; }
        public string item_store_box { get; set; }
        public string item_store_shif { get; set; }
        public Nullable<bool> item_store_state { get; set; }
        public string item_store_note { get; set; }
        public Nullable<decimal> item_id { get; set; }
        public Nullable<decimal> store_bra_id { get; set; }
    
        public virtual T_ITEMS T_ITEMS { get; set; }
        public virtual T_STORE_BRANCH T_STORE_BRANCH { get; set; }
    }
}
