//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ITEM_DETAILS
    {
        public decimal item_details_id { get; set; }
        public Nullable<decimal> item_details_code { get; set; }
        public string item_details_city { get; set; }
        public Nullable<System.DateTime> item_details_production_date { get; set; }
        public Nullable<System.DateTime> item_details_end_date { get; set; }
        public string item_details_series { get; set; }
        public string item_details_company { get; set; }
        public string item_details_warnty { get; set; }
        public Nullable<decimal> item_id { get; set; }
    
        public virtual T_ITEMS T_ITEMS { get; set; }
    }
}
