//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ITEM_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ITEM_TYPE()
        {
            this.T_ITEMS = new HashSet<T_ITEMS>();
        }
    
        public decimal item_type_id { get; set; }
        public Nullable<decimal> item_type_code { get; set; }
        public string item_type { get; set; }
        public Nullable<bool> item_type_state { get; set; }
        public string item_type_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ITEMS> T_ITEMS { get; set; }
    }
}
