//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ITEM_BARCODE
    {
        public decimal bar_id { get; set; }
        public Nullable<decimal> bar_code { get; set; }
        public string bar_num { get; set; }
        public string bar_type { get; set; }
        public Nullable<bool> bar_state { get; set; }
        public string bar_note { get; set; }
        public Nullable<decimal> item_id { get; set; }
    
        public virtual T_ITEMS T_ITEMS { get; set; }
    }
}
