//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MAIN_CASH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_MAIN_CASH()
        {
            this.T_BANK_ACOUNT = new HashSet<T_BANK_ACOUNT>();
            this.T_CASH_ACOUNT = new HashSet<T_CASH_ACOUNT>();
            this.T_CASH_TRANSACTION = new HashSet<T_CASH_TRANSACTION>();
        }
    
        public decimal cash_id { get; set; }
        public Nullable<decimal> cash_code { get; set; }
        public Nullable<System.DateTime> cash_start_date { get; set; }
        public Nullable<decimal> cash_start_balance { get; set; }
        public Nullable<decimal> cash_zero_balance { get; set; }
        public Nullable<decimal> cash_balance { get; set; }
        public Nullable<bool> cash_state { get; set; }
        public string cash_note { get; set; }
        public Nullable<decimal> bran_id { get; set; }
        public string cash_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BANK_ACOUNT> T_BANK_ACOUNT { get; set; }
        public virtual T_BRANCH T_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CASH_ACOUNT> T_CASH_ACOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CASH_TRANSACTION> T_CASH_TRANSACTION { get; set; }
    }
}
