//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STORE_ENTRY_TRANSAQTION
    {
        public decimal entry_trans_id { get; set; }
        public Nullable<decimal> entry_trans_code { get; set; }
        public Nullable<System.DateTime> entry_trans_date { get; set; }
        public Nullable<System.TimeSpan> entry_trans_time { get; set; }
        public string entry_trans_text { get; set; }
        public Nullable<bool> entry_trans_state { get; set; }
        public Nullable<decimal> bond_id { get; set; }
        public Nullable<decimal> bond_type_id { get; set; }
    
        public virtual T_BONDS_TYPE T_BONDS_TYPE { get; set; }
    }
}
