//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TAX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TAX()
        {
            this.T_TAX_TRANSACTION = new HashSet<T_TAX_TRANSACTION>();
        }
    
        public decimal tax_id { get; set; }
        public Nullable<decimal> tax_code { get; set; }
        public string tax_name { get; set; }
        public Nullable<System.DateTime> tax_date { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_per { get; set; }
        public Nullable<bool> tax_state { get; set; }
        public string tax_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TAX_TRANSACTION> T_TAX_TRANSACTION { get; set; }
    }
}
