//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TAX_TRANSACTION
    {
        public decimal tax_tran_id { get; set; }
        public Nullable<decimal> tax_tran_code { get; set; }
        public Nullable<System.DateTime> tax_tran_date { get; set; }
        public Nullable<System.TimeSpan> tax_tran_time { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax_value { get; set; }
        public Nullable<decimal> tax_net { get; set; }
        public Nullable<decimal> tax_id { get; set; }
        public Nullable<bool> tax_tran_state { get; set; }
        public string tax_tran_note { get; set; }
    
        public virtual T_TAX T_TAX { get; set; }
    }
}
