//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRED_TYPE
    {
        public decimal tred_id { get; set; }
        public Nullable<decimal> tred_code { get; set; }
        public string tred_type { get; set; }
        public Nullable<bool> tred_state { get; set; }
        public string tred_note { get; set; }
    }
}
