//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_ACC_DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_VENDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_VENDOR()
        {
            this.T_INVOICE_PAY = new HashSet<T_INVOICE_PAY>();
            this.T_INVOICE_PAY_BACK_TRANSACTION = new HashSet<T_INVOICE_PAY_BACK_TRANSACTION>();
            this.T_INVOICE_PAY_TRANSACTION = new HashSet<T_INVOICE_PAY_TRANSACTION>();
        }
    
        public decimal ven_id { get; set; }
        public Nullable<decimal> ven_code { get; set; }
        public string ven_name { get; set; }
        public string ven_nick_name { get; set; }
        public string ven_majore { get; set; }
        public string ven_adress { get; set; }
        public string ven_mobile { get; set; }
        public string ven_mobile1 { get; set; }
        public string tax_nation_num { get; set; }
        public Nullable<bool> ven_state { get; set; }
        public string ven_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY> T_INVOICE_PAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_BACK_TRANSACTION> T_INVOICE_PAY_BACK_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_INVOICE_PAY_TRANSACTION> T_INVOICE_PAY_TRANSACTION { get; set; }
    }
}
